### PR TITLE
Minor corrections to the UHFQA driver

### PR DESCRIPTION
**Pull request by abdurakhimov**
1) Added support for dead_time and latency parameters
2) Fixed tooltips for 'QA Monitor - Averages' and 'QA Results - HW Averages'
3) Added the code to provide proper time arrays for 'QA Monitor - Input 1' and 'QA Monitor - Input 2' data.

### CODE REVIEW

**Comment by katetsu** [comment]
Thanks a lot for your PR. we appreciate your contribution.
Could you please provide some background information to why this PR is needed. particularly, why do we need "sequencer dead time"? and what it actually means.

**Comment by abdurakhimov** [comment]
1.  Added support for 'dead_time' and 'latency' parameters
Please see details about 'dead_time' and 'latency' parameters in the documentation for sequence parameters [here](https://docs.zhinst.com/zhinst-toolkit/en/latest/examples/notebooks/example3-1_SequenceParameters.html) and [here](https://docs.zhinst.com/zhinst-toolkit/en/latest/zhinst-toolkit/awg.html). 
If a user wants to control the position of the time origin t=0 relative to the trigger signal, the support for the dead_time parameter is needed. In particular, if a user wants the time origin to start immediately after the trigger signal, they need to set dead_time value to the difference between the period and latency times, dead_time = period - latency. 
As a general remark, zhinst-labber drivers should give access to all available parameters provided by zhinst-toolkit for a given instrument. The current version of zhinst-labber is very limited in that sense. 
2.  Fixed tooltips for 'QA Monitor - Averages' and 'QA Results - HW Averages'
Tooltips for 'QA Monitor - Averages' and 'QA Results - HW Averages' are outdated. Apparently, the definitions of those parameter have been changed. Currently, those parameters correspond to a number of averages (not to log2() of the number of averages).
3. Added the code to provide proper time arrays for 'QA Monitor - Input 1' and 'QA Monitor - Input 2' data.
In Labber, it is assumed that instruments such as a signal generator, a digitizer, etc., return data array with additional time array. Please see the description of getTraceDict() [here](http://labber.org/online-doc/html/Drivers.html). In that case, a user can do signal processing using Labber interface (e.g., FFT).

**Comment by katetsu** [comment]
Hi, Sorry for the long delay. the PR looks good to me,
Could you please revise your commit messages to show what has been done
something like:

- Add support for 'dead_time' and 'latency' parameters
- Fix tooltips for 'QA Monitor - Averages' and 'QA Results
- Add the code to provide proper time arrays for 'QA Monitor'

please add the above descriptions to your relative commit bodies

**Comment by abdurakhimov** [comment]
I will recreate commits with correct commit messages, and I will create a new pull request.

**Pull request closed without merging**
